# Cómo cargar datos en Python

Es muy útil poder leer datos, pero es aún más útil poder modificarlos a nuestro antojo.

Hay varias maneras de hacer esto,usando diferentes módulos de Python.

# Usando Numpy

Podemos generar datos dentro de Python usando Numpy y luego guardándolos en algún archivo, cuya extensión es ```.npy``` (Qué raro) para luego volver a cargarlo en otro Notebook o Script.

**Ejemplo:**

In [4]:
import numpy as np


data = np.array([[1, 2, 3], [4, 5, 6]])

np.save('Datos/test2', data)

In [6]:
x = np.load('Datos/test2.npy')

print("Data =\n\n",x)

Data =

 [[1 2 3]
 [4 5 6]]


In [7]:
%whos

Variable   Type       Data/Info
-------------------------------
data       ndarray    2x3: 6 elems, type `int32`, 24 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
x          ndarray    2x3: 6 elems, type `int32`, 24 bytes


**Juguemos** con los datos:

In [36]:
sumita = np.sum(x)
produc = 2*x
potenc = x**2
promed = np.average(x)
stdevi = np.std(x)

print("La suma es:", sumita,"\n")
print("El Producto es:\n\n", produc,"\n")
print("La Potencia es:\n\n", potenc,"\n")
print("El promedio es:", promed,"\n")
print("La Desviación estándar es:", stdevi)

La suma es: 21 

El Producto es:

 [[ 2  4  6]
 [ 8 10 12]] 

La Potencia es:

 [[ 1  4  9]
 [16 25 36]] 

El promedio es: 3.5 

La Desviación estándar es: 1.707825127659933


También podríamos haber usado el atributo ```loadtxt``` para leer archivos .txt:

In [15]:
x=np.loadtxt("Datos/data.txt")
print("Data =\n\n",x)
#Notar los puntos

Data =

 [1. 2. 3. 4. 5.]


# Usando CSV

Numpy es un poco celoso para leer archivos de otros formatos diferentes de npy y .txt.

En vez de eso, podemos usar el módulo **csv** (comma-separated values) para leer archivos.

Esto es un poco más engorroso, pero sin lugar a dudas vale la pena.

**Nota:** Solo podremos leer datos que contengan elementos numéricos.

In [25]:
import csv

filen = 'Datos/data.txt'
rawdata = open(filen,'r')
reader = csv.reader(rawdata, delimiter=' ')
x = list(reader)

In [27]:

print(x)
data = np.array(x).astype('float')
data

[['1', '2', '3', '4', '5']]


array([[1., 2., 3., 4., 5.]])

In [28]:
%whos

Variable   Type             Data/Info
-------------------------------------
csv        module           <module 'csv' from 'C:\\U<...>\Anaconda3\\lib\\csv.py'>
data       ndarray          1x5: 5 elems, type `float64`, 40 bytes
filen      str              Datos/data.txt
np         module           <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
rawdata    TextIOWrapper    <_io.TextIOWrapper name='<...>de='r' encoding='cp1252'>
reader     reader           <_csv.reader object at 0x000001EAB22245F8>
x          list             n=1


# Cargar datos desde Internet

Para esto, basta suministrar la dirección url donde se encuentran alojados los datos e importar ciertos atributos del módulo **urllib**:

In [29]:
from numpy import loadtxt
from urllib.request import urlopen

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'

rawdata=urlopen(url)

data2 = loadtxt(rawdata, delimiter=",")

print(data2)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


In [30]:
url2='https://raw.githubusercontent.com/ucmadcursoPythonyR/2020/master/Datos/iris.csv'

In [33]:
rawdata2=urlopen(url2)
rawdata2

In [42]:
reader2 = csv.reader(rawdata2, delimiter=',',newline='')
reader2
for row in reader2:
        print(row)

TypeError: 'newline' is an invalid keyword argument for this function

# Tarea

- Hacer el mismo proceso usando la librería pandas
- ¿Por qué es tan famoso pandas?
- Haga un análisis estadístico descriptivo de un conjunto grande datos